language: cpp
compiler: gcc
os: linux
dist: xenial
sudo: required

before_install:
  - "sudo add-apt-repository -y ppa:freecad-community/ppa"
  - sudo apt-get update -qq


install:
  - |
    sudo apt-get install -y \
    libocct-data-exchange-dev libocct-foundation-dev libocct-modeling-algorithms-dev libocct-modeling-data-dev \
    libboost-system-dev libboost-program-options-dev libboost-regex-dev libboost-thread-dev libboost-date-time-dev libboost-iostreams-dev libboost-filesystem-dev \
    build-essential cmake libicu-dev python2.7 libpython2.7-dev swig zlib1g liblzma5 opencollada-dev


script:
  - pwd
  - cd cmake
  - mkdir build
  - cd build
  - |
    cmake \
    -DOCC_INCLUDE_DIR=/usr/include/occt \
    -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu \
    -DPYTHON_EXECUTABLE=/usr/bin/python2.7 \
    -DLIBXML2_INCLUDE_DIR=/usr/include/libxml2 \
    -DLIBXML2_LIBRARIES="/usr/lib/x86_64-linux-gnu/libxml2.a;/lib/x86_64-linux-gnu/libz.so.1;/lib/x86_64-linux-gnu/liblzma.so.5" \
    ..
  - sudo make install
    
  - cd ../../test
  - /usr/bin/python2.7 tests.py

  - cd input
  - |
    for i in *.ifc; do \
    echo $i
    /usr/local/bin/IfcConvert -yv "$i" "$i.dae" --validate
    done