package:
  name: ifcopenshell
  version: "0.6.0a0"

source:
  git_rev: "v0.6.0a0"
  git_url: https://github.com/IfcOpenShell/IfcOpenShell

build:
  number: 0
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py35]
    - vc14    # [win and py36]

requirements:
  build:
    - gcc     # [osx]
    - make
    - python
    - oce ==0.17.3
    - cmake
    - swig >=3.0.9
    - libboost
    - icu
  run:
    - libgcc  # [osx]
    - python
    - oce ==0.17.3
    - libboost
    - icu

about:
  home: http://ifcopenshell.org
  license: LGPL
